# Cyclistic
Google Data Analytics Capstone Project
library(tidyverse) 
library(lubridate)
library(moments)  # for skewness and kurtosis
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Read and Combine the 12 Montly csv files
# Get a list of all CSV files in the directory
file_list <- list.files(path = "/kaggle/input/cyclistic-bike-share/", pattern = "*.csv", full.names = TRUE)

# Read in and combine all files into one data frame
combined_data <- file_list %>% 
  map_df(~read_csv(.))
Rows: 337230 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 531633 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 729595 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 822410 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 804352 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 756147 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 631226 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 359978 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 247540 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 103770 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 115609 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 284042 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
dim(combined_data)
572353213
combined_data <-  combined_data%>%
  filter(!is.na (start_station_name))
dim(combined_data)
497815613
combined_data$end_date <- as.Date(combined_data$ended_at)
combined_data$start_date <- as.Date(combined_data$started_at)
# 4978156
combined_data <- combined_data %>%
  filter(start_date == end_date)
dim(combined_data)
493918515
summary(combined_data)
   ride_id          rideable_type        started_at                 
 Length:4939185     Length:4939185     Min.   :2021-04-01 00:03:18  
 Class :character   Class :character   1st Qu.:2021-06-20 09:15:25  
 Mode  :character   Mode  :character   Median :2021-08-14 17:54:56  
                                       Mean   :2021-08-24 02:47:52  
                                       3rd Qu.:2021-10-10 11:46:07  
                                       Max.   :2022-03-31 23:53:00  
                                                                    
    ended_at                   start_station_name start_station_id  
 Min.   :2021-04-01 00:14:29   Length:4939185     Length:4939185    
 1st Qu.:2021-06-20 09:40:46   Class :character   Class :character  
 Median :2021-08-14 18:18:58   Mode  :character   Mode  :character  
 Mean   :2021-08-24 03:06:35                                        
 3rd Qu.:2021-10-10 12:19:06                                        
 Max.   :2022-03-31 23:58:41                                        
                                                                    
 end_station_name   end_station_id       start_lat       start_lng     
 Length:4939185     Length:4939185     Min.   :41.65   Min.   :-87.83  
 Class :character   Class :character   1st Qu.:41.88   1st Qu.:-87.66  
 Mode  :character   Mode  :character   Median :41.90   Median :-87.64  
                                       Mean   :41.90   Mean   :-87.64  
                                       3rd Qu.:41.93   3rd Qu.:-87.63  
                                       Max.   :45.64   Max.   :-73.80  
                                                                       
    end_lat         end_lng       member_casual         end_date         
 Min.   :41.39   Min.   :-88.97   Length:4939185     Min.   :2021-04-01  
 1st Qu.:41.88   1st Qu.:-87.66   Class :character   1st Qu.:2021-06-20  
 Median :41.90   Median :-87.64   Mode  :character   Median :2021-08-14  
 Mean   :41.90   Mean   :-87.64                      Mean   :2021-08-23  
 3rd Qu.:41.93   3rd Qu.:-87.63                      3rd Qu.:2021-10-10  
 Max.   :42.17   Max.   :-87.50                      Max.   :2022-03-31  
 NA's   :1467    NA's   :1467                                            
   start_date        
 Min.   :2021-04-01  
 1st Qu.:2021-06-20  
 Median :2021-08-14  
 Mean   :2021-08-23  
 3rd Qu.:2021-10-10  
 Max.   :2022-03-31  
                     
combined_data <- combined_data  %>%
  select(-c(ride_id, end_station_name, end_station_id, end_lat, end_lng))
names(combined_data)
'rideable_type''started_at''ended_at''start_station_name''start_station_id''start_lat''start_lng''member_casual''end_date''start_date'



# Creating time-based features
combined_data <- combined_data %>%
  mutate(
    start_hour = hour(started_at),
    end_hour = hour(ended_at),
    
    start_day = day(started_at),
    end_day = day(ended_at),
    
    start_month = month(started_at),
    end_month = month(ended_at),
    
    start_year = year(started_at),
    end_year = year(ended_at),
    
    start_weekday = wday(started_at, label = TRUE),
    end_weekday = wday(ended_at, label = TRUE),
    
    is_weekend_start = ifelse(start_weekday %in% c("Sat", "Sun"), 1, 0),
    is_weekend_end = ifelse(end_weekday %in% c("Sat", "Sun"), 1, 0)
  )

# Displaying the first few rows of the transformed data
head(data)
                                                                            
1 function (..., list = character(), package = NULL, lib.loc = NULL,        
2     verbose = getOption("verbose"), envir = .GlobalEnv, overwrite = TRUE) 
3 {                                                                         
4     fileExt <- function(x) {                                              
5         db <- grepl("\\\\.[^.]+\\\\.(gz|bz2|xz)$", x)                     
6         ans <- sub(".*\\\\.", "", x)                                      
head(combined_data)
A tibble: 6 × 22
rideable_type	started_at	ended_at	start_station_name	start_station_id	start_lat	start_lng	member_casual	end_date	start_date	⋯	start_day	end_day	start_month	end_month	start_year	end_year	start_weekday	end_weekday	is_weekend_start	is_weekend_end
<chr>	<dttm>	<dttm>	<chr>	<chr>	<dbl>	<dbl>	<chr>	<date>	<date>	⋯	<int>	<int>	<dbl>	<dbl>	<dbl>	<dbl>	<ord>	<ord>	<dbl>	<dbl>
classic_bike	2021-04-12 18:25:36	2021-04-12 18:56:55	State St & Pearson St   	TA1307000061	41.89745	-87.62872	member	2021-04-12	2021-04-12	⋯	12	12	4	4	2021	2021	Mon	Mon	0	0
docked_bike	2021-04-27 17:27:11	2021-04-27 18:31:29	Dorchester Ave & 49th St	KA1503000069	41.80577	-87.59246	casual	2021-04-27	2021-04-27	⋯	27	27	4	4	2021	2021	Tue	Tue	0	0
classic_bike	2021-04-17 09:17:42	2021-04-17 09:42:48	Honore St & Division St	TA1305000034	41.90312	-87.67394	member	2021-04-17	2021-04-17	⋯	17	17	4	4	2021	2021	Sat	Sat	1	1
docked_bike	2021-04-03 12:42:25	2021-04-03 14:13:42	Loomis Blvd & 84th St   	20121       	41.74149	-87.65841	casual	2021-04-03	2021-04-03	⋯	3	3	4	4	2021	2021	Sat	Sat	1	1
classic_bike	2021-04-25 18:43:18	2021-04-25 18:43:59	Clinton St & Polk St    	15542       	41.87147	-87.64095	casual	2021-04-25	2021-04-25	⋯	25	25	4	4	2021	2021	Sun	Sun	1	1
classic_bike	2021-04-03 16:28:21	2021-04-03 16:29:47	Ashland Ave & 63rd St   	16948       	41.77937	-87.66484	casual	2021-04-03	2021-04-03	⋯	3	3	4	4	2021	2021	Sat	Sat	1	1
# Calculating the trip duration in minutes
combined_data <- combined_data %>%
  mutate(trip_duration = as.numeric(difftime(ended_at, started_at, units = "mins")))
combined_data <-  combined_data %>%
  mutate(trip_duration = abs(trip_duration))

combined_data <- combined_data %>% filter(trip_duration > 1)
# Displaying the first few rows of the data with the new column
summary(combined_data$trip_duration)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
   1.017    6.917   12.033   18.971   21.683 1424.700 
desciptive statastic on trip_duration
library(moments)  # for skewness and kurtosis

desc_stats <- combined_data %>%
  summarise(
    Mean = mean(trip_duration, na.rm = TRUE),
    Median = median(trip_duration, na.rm = TRUE),
    Min = min(trip_duration, na.rm = TRUE),
    Max = max(trip_duration, na.rm = TRUE),
    Q1 = quantile(trip_duration, 0.25, na.rm = TRUE),
    Q3 = quantile(trip_duration, 0.75, na.rm = TRUE),
    IQR = Q3 - Q1,
    Std_Dev = sd(trip_duration, na.rm = TRUE),
    Variance = var(trip_duration, na.rm = TRUE),
    Range = Max - Min,
    Skewness = skewness(trip_duration, na.rm = TRUE),
    Kurtosis = kurtosis(trip_duration, na.rm = TRUE)
  )

desc_stats
A tibble: 1 × 12
Mean	Median	Min	Max	Q1	Q3	IQR	Std_Dev	Variance	Range	Skewness	Kurtosis
<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>
18.97121	12.03333	1.016667	1424.7	6.916667	21.68333	14.76667	26.17043	684.8912	1423.683	9.199857	197.2369


library(ggthemes)

# 1. Histogram
ggplot(combined_data, aes(x = trip_duration)) +
  geom_histogram(binwidth = 5, fill = "blue", color = "black", alpha = 0.7) +
  theme_minimal() +
  labs(title = "Distribution of Trip Duration", x = "Trip Duration (minutes)", y = "Number of Rides")

# 2. Boxplot
ggplot(combined_data, aes(y = trip_duration)) +
  geom_boxplot(fill = "blue", color = "black", alpha = 0.7) +
  theme_minimal() +
  labs(title = "Boxplot of Trip Duration", x = "", y = "Trip Duration (minutes)")

# 3. Density Plot
ggplot(combined_data, aes(x = trip_duration)) +
  geom_density(fill = "blue", alpha = 0.7) +
  theme_minimal() +
  labs(title = "Density Plot of Trip Duration", x = "Trip Duration (minutes)", y = "Density")

# 4. Bar Plot for Hour of the Day
ggplot(combined_data, aes(x = start_hour)) +
  geom_bar(fill = "blue", color = "black", alpha = 0.7) +
  theme_minimal() +
  labs(title = "Number of Rides per Hour", x = "Hour of the Day", y = "Number of Rides")

#Analyze
#Goal: Use data to extract valuable patterns or findings that can inform decision-making and achieve positive outcomes

usercount <- BikeShare %>%
  group_by(user) %>%
  summarize(total = n()) %>%
  mutate(overall_total = sum(total)) %>%
  group_by(user) %>%
  summarize(percent_total = total / overall_total)

bike_usage <- BikeShare %>%
  group_by(bike) %>%
  summarize(total = n()) %>%
  mutate(overall_total = sum(total)) %>%
  group_by(bike) %>%
  summarize(percent_total = total / overall_total)

bike_usage
A tibble: 3 × 2
bike	percent_total
<chr>	<dbl>
classic_bike	0.69849453
docked_bike	0.06539499
electric_bike	0.23611048

casual_member_biketype_used <- BikeShare %>%
    filter(user == "casual") %>%
    group_by(bike) %>%
    summarize(total = n()) %>%
    mutate(percent_casual = total / sum(total))

casual_member_biketype_used
A tibble: 3 × 3
bike	total	percent_casual
<chr>	<int>	<dbl>
classic_bike	1252609	0.6127208
docked_bike	303524	0.1484705
electric_bike	488206	0.2388087
annual_member_biketype_used <- BikeShare %>%
  filter(user == "member") %>%
  group_by(bike) %>%
  summarize(total = n()) %>%
  mutate(overall_total = sum(total)) %>%
  mutate(percent_member = total / overall_total)

annual_member_biketype_used
A tibble: 2 × 4
bike	total	overall_total	percent_member
<chr>	<int>	<int>	<dbl>
classic_bike	1989380	2597056	0.7660135
electric_bike	607676	2597056	0.2339865
riders_time_user <- BikeShare %>%
  group_by(user) %>%
  summarize(avg_time = mean(ride_length), .groups = "drop")

riders_time_user$avg_time <- round(riders_time_user$avg_time, digits = 0)

riders_time_user
A tibble: 2 × 2
user	avg_time
<chr>	<dbl>
casual	32
member	13
riders_time_biketypes <- BikeShare %>%
  group_by(bike, user) %>%
  summarize(avg_time = mean(ride_length), .groups = "drop")

riders_time_biketypes$avg_time <- round(riders_time_biketypes$avg_time, digits = 0)

riders_time_biketypes
A tibble: 5 × 3
bike	user	avg_time
<chr>	<chr>	<dbl>
classic_bike	casual	26
classic_bike	member	13
docked_bike	casual	77
electric_bike	casual	20
electric_bike	member	12
Average ride time by user
avgridetime <- BikeShare %>%
  group_by(user) %>%
  summarise(avgtime = mean(ride_length))

avgridetime$avgtime <- round(avgridetime$avgtime, digits = 0)

avgridetime
A tibble: 2 × 2
user	avgtime
<chr>	<dbl>
casual	32
member	13
Rides by user, hour
hour <- BikeShare %>%
  group_by(user, hour) %>% 
  summarise(numberofrides = n(), .groups = 'drop') %>% 
  arrange(hour)

hour
A tibble: 48 × 3
user	hour	numberofrides
<chr>	<chr>	<int>
casual	00	47202
member	00	28294
casual	01	34741
member	01	18008
casual	02	24616
member	02	10949
casual	03	13144
member	03	5756
casual	04	8058
member	04	5656
casual	05	8214
member	05	21826
casual	06	16972
member	06	63550
casual	07	31640
member	07	123805
casual	08	45819
member	08	161308
casual	09	51651
member	09	117483
casual	10	70508
member	10	104194
casual	11	97063
member	11	121657
casual	12	122945
member	12	145901
casual	13	134890
member	13	144421
casual	14	142482
member	14	141319
casual	15	151146
member	15	160346
casual	16	164706
member	16	208444
casual	17	192268
member	17	275253
casual	18	188556
member	18	245403
casual	19	151357
member	19	178910
casual	20	110876
member	20	119798
casual	21	88735
member	21	85576
casual	22	80822
member	22	64619
casual	23	65928
member	23	44580
Creation of trip count table by day of the week and user type
dayofweek <- BikeShare %>%
  group_by(user, day_of_week) %>%
  summarise(numberofrides = n(), .groups = "drop")
view(dayofweek)
Creation of trip count table by user and month
month <- BikeShare %>%
  group_by(user, month) %>%
  summarise(numberofrides = n(), .groups = "drop")
Removing rows with missing values in the month column
month <- na.omit(month)
Cleaned table view
month
A tibble: 24 × 3
user	month	numberofrides
<chr>	<ord>	<int>
casual	Jan	12605
casual	Feb	15144
casual	Mar	67156
casual	Apr	120420
casual	May	216829
casual	Jun	304192
casual	Jul	369415
casual	Aug	341476
casual	Sep	292931
casual	Oct	189117
casual	Nov	69978
casual	Dec	45076
member	Jan	67523
member	Feb	74034
member	Mar	148827
member	Apr	177787
member	May	234165
member	Jun	304586
member	Jul	322906
member	Aug	332933
member	Sep	328219
member	Oct	288855
member	Nov	185926
member	Dec	131295
Example data
data <- data.frame(
  tipo_rider = c("casual", "member", "casual", "member", "casual"),
  count = c(15, 25, 10, 35, 20)
)
ggplot(data, aes(x = tipo_rider, y = count, fill = tipo_rider)) +
  geom_col() +
  labs(x = "Tipo Rider", y = "Conteggio") +
  scale_fill_manual(values = c("cadetblue1", "cornflowerblue"))
No description has been provided for this image
Primary Goal
Utilize data visualization techniques to effectively communicate insights and trends derived from the data analysis to

Relevant Stakeholders. By presenting the information in a visually compelling and easily understandable format, the objective is to

Facilitate Informed decision-making and foster productive discussions among stakeholders

# Chunk 1
options(repr.plot.width = 10, repr.plot.height = 6)

ggplot(bike_usage, aes(x = bike, y = percent_total, fill = "#91d8e0")) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(percent_total)), vjust = 1.35, size = 8, fontface = "bold", color = "grey20") + 
  labs(title = "Percentage of bike-used by casual riders", subtitle = "Seven out of ten riders used the classic bike on rides over the last twelve months",
        x = "Types of bikes", y = "") +
  theme_minimal() +
  theme(plot.title = element_text(size = 22, color = "#42a0ab", face = "bold"), 
        plot.subtitle = element_text(size = 16, color = "grey20", face = "bold"), 
        plot.caption = element_text(size = 8, color = "grey35"),
        axis.text.x = element_text(size = 14, color = "grey20", face = "bold"),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 15, color = "#42a0ab", face = "bold"), 
        axis.title.y = element_blank(),
        legend.position = "none")
No description has been provided for this image
# Chunk 2
options(repr.plot.width = 10, repr.plot.height = 6)

ggplot(casual_member_biketype_used, aes(x = bike, y = percent_casual, fill = percent_casual)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(percent_casual)), vjust = 2, size = 8, fontface = "bold", color = "grey20") + 
  scale_fill_gradient(high = "#42a0ab", low = "#91d8e0") +
  labs(title = "Percentage of bike-used by casual riders", subtitle = "Casual riders majority pick the classic bike for there ride",
       x = "Types of bikes", y = "") +
  theme_minimal() +
  theme(plot.title = element_text(size = 22, color = "#42a0ab", face = "bold"), 
        plot.subtitle = element_text(size = 16, color = "grey20", face = "bold"), 
        plot.caption = element_text(size = 8, color = "grey35"),
        axis.title.x = element_text(size = 15, color = "#42a0ab", face = "bold"),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 14, color = "grey20", face = "bold"),
        axis.text.y = element_blank(),
        legend.position = "none")
No description has been provided for this image
# Chunk 3
options(repr.plot.width = 8, repr.plot.height = 6)

ggplot(riders_time_user, aes(x = user, y = avg_time, fill = avg_time)) +
  geom_col(width = 0.8) + 
  geom_text(aes(label = avg_time), vjust = 2, size = 8, color = "grey20", fontface = "bold") +
  scale_fill_gradient(high = "#42a0ab", low = "#91d8e0") +
  labs(title = "Average time spent by riders on bikes", subtitle = "Casual riders spend twice as long as members on average",
        x = "User", y = "Time (mins)") +
  theme_minimal() +
  theme(plot.title = element_text(size = 22, color = "#42a0ab", face = "bold"), 
        plot.subtitle = element_text(size = 14, color = "grey20", face = "bold"), 
        plot.caption = element_text(size = 8, color = "grey35"),
        axis.title.x = element_text(size = 15, color = "#42a0ab", face = "bold"), 
        axis.title.y = element_text(size = 15, color = "#42a0ab", face = "bold"), 
        axis.text.x = element_text(size = 14, color = "grey20", face = "bold"),
        axis.text.y = element_blank(),
        legend.position = "none")
No description has been provided for this image
# Chunk 4
options(repr.plot.width = 8, repr.plot.height = 6)

ggplot(riders_time_biketypes, aes(x = bike, y = avg_time, fill = avg_time)) +
  geom_col() + 
  geom_text(aes(label = avg_time), vjust = 2, size = 8, color = "grey20", fontface = "bold") +
  scale_fill_gradient(high = "#42a0ab", low = "#91d8e0") +
  facet_wrap(~user) +
  labs(title = "Average time spent by riders on bikes", 
       subtitle = "Both casual and members ride the electric bike the farthest",
       x = "Type of Bike", y = "Average time spent (mins)") +
  theme_minimal() +
  theme(plot.title = element_text(size = 22, color = "#42a0ab", face = "bold"), 
        plot.subtitle = element_text(size = 16, color = "grey20", face = "bold"), 
        plot.caption = element_text(size = 8, color = "grey35"),
        axis.title.x = element_text(size = 15, color = "#42a0ab", face = "bold"), 
        axis.text.x = element_text(size = 10, color = "grey20", face = "bold"))
No description has been provided for this image
# Chunk 8
options(repr.plot.width = 12, repr.plot.height = 8)
options(scipen=999)

ggplot(dayofweek, aes(day_of_week, numberofrides, fill = user, group = user)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("#91d8e0", "#42a0ab"), name = "Types of riders", breaks = c("casual", "member"), labels = c("Casual Member", "Annual Member")) +
  labs(title = "Day of the Week Riders", subtitle = "Rides happened the most during the weekend",
       
       x = "Day of Week", y = "Number of Rides") +
  theme_minimal() +
  theme(plot.title = element_text(size = 22, color = "#42a0ab", face = "bold"), 
        plot.subtitle = element_text(size = 14, color = "grey20", face = "bold"), 
        plot.caption = element_text(size = 8, color = "grey35"),
        legend.title = element_text(size = 16, face = "bold", color = "#42a0ab"),
        legend.text = element_text(size = 14, color = "grey20"),
        axis.title.x = element_text(size = 15, color = "#42a0ab", face = "bold"), 
        axis.title.y = element_text(size = 15, color = "#42a0ab", face = "bold"),
        axis.text.x = element_text(size = 10, color = "grey20", face = "bold"),
        axis.text.y = element_text(size = 10, color = "grey20", face = "bold"))
No description has been provided for this image
# Chunk 9
options(repr.plot.width = 12, repr.plot.height = 8)
options(scipen=999)

ggplot(month, aes(month, numberofrides, fill = user, group = user)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("#91d8e0", "#42a0ab"), name = "Types of riders", breaks = c("casual", "member"), labels = c("Casual Member", "Annual Member")) +
  labs(title = "Monthly Rides",
        subtitle = "The summer months have the most number of rides",
       x = "Month", y = "Number of Rides") +
  theme_minimal() +
  theme(plot.title = element_text(size = 22, color = "#42a0ab", face = "bold"), 
        plot.subtitle = element_text(size = 14, color = "grey20", face = "bold"), 
        plot.caption = element_text(size = 8, color = "grey35"),
        legend.title = element_text(size = 16, face = "bold", color = "#42a0ab"),
        legend.text = element_text(size = 14, color = "grey20"),
        axis.title.x = element_text(size = 15, color = "#42a0ab", face = "bold"), 
        axis.title.y = element_text(size = 15, color = "#42a0ab", face = "bold"),
        axis.text.x = element_text(size = 10, color = "grey20", face = "bold"),
        axis.text.y = element_text(size = 10, color = "grey20", face = "bold"))


